name: Docker Image CI

on:
  release:
    types: [published]

jobs:
  build-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Prepare and build the container hashed image
        run: ./builder.sh handler ghcr.io/${{ env.REPO }}-handler:${{ github.sha }}
      - name: Prepare and build the container latest image
        run: ./builder.sh handler ghcr.io/${{ env.REPO }}-handler:latest

  build-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PUSH }}

      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: Prepare and build the container hashed image
        run: ./builder.sh checker ghcr.io/${{ env.REPO }}-checker:${{ github.sha }}
      - name: Prepare and build the container latest image
        run: ./builder.sh checker ghcr.io/${{ env.REPO }}-checker:latest

  deploy-stack:
    runs-on: ubuntu-latest
    needs: [build-handler, build-checker, build-reciever]
    steps:
      - name: Invoke deployment hook
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
